import type { Metadata } from "next";
import "./globals.css"
import IsUserLogin from "@/contexts/IsUserLogin";
import ReduxProvider from "@/redux/ReduxProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ReduxProvider>
          <IsUserLogin>
            {children}
          </IsUserLogin>
        </ReduxProvider>
      </body>
    </html>
  );
}
